Traceback (most recent call last):
  File "/home/user/mambaforge/envs/mdd/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/user/mambaforge/envs/mdd/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/user/mambaforge/envs/mdd/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/home/user/mambaforge/envs/mdd/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/mambaforge/envs/mdd/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/user/mambaforge/envs/mdd/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/user/mambaforge/envs/mdd/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
a = np.arange(2)

colors = matplotlib.rcParams['axes.color_cycle']
plt.figure(figsize=(12,8))
for i, p in enumerate([0.1, 0.2, 0.6, 0.7]):
    ax = plt.subplot(1, 4, i+1)
    plt.bar(a, bernoulli.pmf(a, p), label=p, color=colors[i], alpha=0.5)
    ax.xaxis.set_ticks(a)

    plt.legend(loc=0)
    if i == 0:
        plt.ylabel("PDF at $k$")
    

plt.suptitle("Bernoulli probability")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[5], line 3[0m
[1;32m      1[0m a [38;5;241m=[39m np[38;5;241m.[39marange([38;5;241m2[39m)
[0;32m----> 3[0m colors [38;5;241m=[39m [43mmatplotlib[49m[38;5;241;43m.[39;49m[43mrcParams[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43maxes.color_cycle[39;49m[38;5;124;43m'[39;49m[43m][49m
[1;32m      4[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m12[39m,[38;5;241m8[39m))
[1;32m      5[0m [38;5;28;01mfor[39;00m i, p [38;5;129;01min[39;00m [38;5;28menumerate[39m([[38;5;241m0.1[39m, [38;5;241m0.2[39m, [38;5;241m0.6[39m, [38;5;241m0.7[39m]):

File [0;32m~/mambaforge/envs/mdd/lib/python3.10/site-packages/matplotlib/__init__.py:762[0m, in [0;36mRcParams.__getitem__[0;34m(self, key)[0m
[1;32m    759[0m         [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt
[1;32m    760[0m         plt[38;5;241m.[39mswitch_backend(rcsetup[38;5;241m.[39m_auto_backend_sentinel)
[0;32m--> 762[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get[49m[43m([49m[43mkey[49m[43m)[49m

File [0;32m~/mambaforge/envs/mdd/lib/python3.10/site-packages/matplotlib/__init__.py:709[0m, in [0;36mRcParams._get[0;34m(self, key)[0m
[1;32m    690[0m [38;5;28;01mdef[39;00m [38;5;21m_get[39m([38;5;28mself[39m, key):
[1;32m    691[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    692[0m [38;5;124;03m    Directly read data bypassing deprecation, backend and validation[39;00m
[1;32m    693[0m [38;5;124;03m    logic.[39;00m
[0;32m   (...)[0m
[1;32m    707[0m [38;5;124;03m    :meta public:[39;00m
[1;32m    708[0m [38;5;124;03m    """[39;00m
[0;32m--> 709[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mdict[39;49m[38;5;241;43m.[39;49m[38;5;21;43m__getitem__[39;49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mkey[49m[43m)[49m

[0;31mKeyError[0m: 'axes.color_cycle'

