Traceback (most recent call last):
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/user/.edm/envs/mdd/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/user/.edm/envs/mdd/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as pl
%pylab inline

import sys
sys.path.append('../../scripts')
from linear_regression import linreg

from IPython.core.display import Image 
Image(filename='../../img/sensitivity_error_example.png',width=400) 
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [1], line 7[0m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m
[1;32m      6[0m sys[38;5;241m.[39mpath[38;5;241m.[39mappend([38;5;124m'[39m[38;5;124m../../scripts[39m[38;5;124m'[39m)
[0;32m----> 7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mlinear_regression[39;00m [38;5;28;01mimport[39;00m linreg
[1;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mimport[39;00m Image 
[1;32m     10[0m Image(filename[38;5;241m=[39m[38;5;124m'[39m[38;5;124m../../img/sensitivity_error_example.png[39m[38;5;124m'[39m,width[38;5;241m=[39m[38;5;241m400[39m)

[0;31mModuleNotFoundError[0m: No module named 'linear_regression'
ModuleNotFoundError: No module named 'linear_regression'

